### ISSUE TITLE
defaultContentLanguage = "ru"

### ISSUE THREAD

**Issue by demetriusk** [jhauraw/axiom#1]
I'm getting `Site config value "ru" for defaultContentLanguage does not match any language definition` error if set `defaultContentLanguage = "ru"` in `config.toml`.
The `i18n/ru.toml` file is existing and not empty. Any ideas? E.g. `fr` works fine.

**Comment by jhauraw** [comment]
@demetriusk post complete config.toml please.

**Comment by demetriusk** [comment]
@jhauraw gotcha! I was stupid and didn't notice these sections at the end (which actually doesn't explain why it worked out for "fr" and didn't for "ru"):

```
[languages]
[languages."en-us"]
weight = 1
languageName = "US English"

```
